# Generated by Django 4.0.3 on 2022-03-15 21:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='полигональная геометрия')),
                ('address', models.CharField(max_length=255, verbose_name='почтовый адреса строения')),
            ],
            options={
                'verbose_name': 'Строение',
                'verbose_name_plural': 'Строения',
            },
        ),
    ]
